---
- name: Prelim Exams
  hosts: managenode
  become: true
  tasks:
  - name: install the latest python3 and pip3 (ubuntu)
    apt:
      name:
        - python3
        - python3-pip
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  - name: install the latest python3 and pip3 (debian)
    dnf:
      name:
        - python3
        - python3-pip
      state: latest
      update_cache: yes
    when: ansible_distribution == "Debian"
  - name: install java's Open-JDK in Ubuntu
    apt:
      name:
        - openjdk-8-jdk
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  - name: install java's Open-JDK in Debian
    dnf:
      name:
        - openjdk-8-jdk
      update_cache: yes
    when: ansible_distribution == "Debian"
  - name: install mariadb on ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  - name: install mariadb on debian
    dnf:
      name:
        - mariadb-server
      state: latest
      update_cache: yes
    when: ansible_distribution == "Debian"
  - name: enable mariadb
    ansible.builtin.systemd:
      name: mariadb
      enabled: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]
  - name: create database in mariadb
    community.mysql.mysql_db:
        name: "Test"
        create:
          name: "Test"
          if_not_exists: yes
  - name: message of the day
    netapp.ontap.na_ontap_motd:
      motd_msg: "Ansible Managed Node by programmy-main"
      hostname: programmy-main
      vserver: managenode

